import { OrbitControls } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import { useEffect, useMemo, useRef, useState } from "react";
import { interpolateArticulation, interpolatePose, poseFromReferencePose, PoseScene } from "./PoseRangeDesigner";

const DEFAULT_ARTICULATION = { face: { jaw_openness: 0, gaze_horizontal: 0, gaze_vertical: 0 }, hand_left: { fist_closure: 0, finger_spread: 1, palm_turn: 0, wrist_rotation: [0, 0, 0] }, hand_right: { fist_closure: 0, finger_spread: 1, palm_turn: 0, wrist_rotation: [0, 0, 0] } };
const OUTLINER_JOINTS = [["head", "Head"], ["shoulder_left", "Left Shoulder"], ["shoulder_right", "Right Shoulder"], ["hip_left", "Left Hip"], ["hip_right", "Right Hip"], ["elbow_left", "Left Elbow"], ["wrist_left", "Left Hand (Wrist)"], ["knee_left", "Left Knee"], ["ankle_left", "Left Ankle"], ["elbow_right", "Right Elbow"], ["wrist_right", "Right Hand (Wrist)"], ["knee_right", "Right Knee"], ["ankle_right", "Right Ankle"]];

export default function GuideSkeletonViewer({ animation = {}, steps = [] }) {
  const frames = useMemo(() => steps.filter((step) => step.reference_pose?.landmarks), [steps]);
  const [playing, setPlaying] = useState(true);
  const [speed, setSpeed] = useState(Number(animation.playback_speed) || 0.75);
  const [elapsed, setElapsed] = useState(0);
  const [selectedJoint, setSelectedJoint] = useState("elbow_left");
  const previousTime = useRef(null);
  useEffect(() => { if (!playing || frames.length < 2) return undefined; let requestId; const tick = (time) => { if (previousTime.current !== null) setElapsed((value) => value + ((time - previousTime.current) * speed)); previousTime.current = time; requestId = window.requestAnimationFrame(tick); }; requestId = window.requestAnimationFrame(tick); return () => { window.cancelAnimationFrame(requestId); previousTime.current = null; }; }, [frames.length, playing, speed]);
  const poseFrames = useMemo(() => frames.map((frame) => poseFromReferencePose(frame.reference_pose)), [frames]);
  const segments = useMemo(() => frames.map((frame, index) => ({ duration: Number(frame.transition_duration_ms) || (index === frames.length - 1 ? 900 : 1000), from: index, to: (index + 1) % frames.length })), [frames]);
  const totalDuration = segments.reduce((sum, segment) => sum + segment.duration, 0) || 1;
  let cursor = elapsed % totalDuration; let activeIndex = 0;
  while (activeIndex < segments.length - 1 && cursor >= segments[activeIndex].duration) { cursor -= segments[activeIndex].duration; activeIndex += 1; }
  const segment = segments[activeIndex];
  const transitionProgress = segment ? cursor / segment.duration : 0;
  const activePose = segment && poseFrames[segment.from] && poseFrames[segment.to] ? interpolatePose(poseFrames[segment.from], poseFrames[segment.to], transitionProgress) : poseFrames[0];
  const guideArticulation = segment ? interpolateArticulation(frames[segment.from]?.reference_pose?.articulation, frames[segment.to]?.reference_pose?.articulation, transitionProgress) : DEFAULT_ARTICULATION;
  const activeStep = frames[activeIndex];
  const targetStep = frames[(activeIndex + 1) % frames.length] || activeStep;
  const progress = Math.min(100, Math.max(0, (elapsed % totalDuration) / totalDuration * 100));
  if (!frames.length) return <div className="guide-skeleton guide-skeleton--empty">Add reference poses to preview this technique.</div>;
  return <section className="guide-skeleton guide-skeleton--workbench" aria-label="Read-only animated technique studio">
    <header className="guide-workbench__toolbar"><strong>POSE WORKBENCH</strong><span className="guide-workbench__hint">Read-only guide studio · Orbit: drag · Pan: right drag · Zoom: wheel</span><nav aria-label="Guide studio tools"><button className="is-active" type="button">Guides</button><button type="button">Panels</button><button type="button">Load</button><button type="button">Fullscreen</button><button onClick={() => setElapsed(0)} type="button">Reset</button></nav></header>
    <div className="guide-workbench__body"><aside className="guide-workbench__outliner"><div className="guide-workbench__panel-title"><strong>OUTLINER</strong><span>POSE</span></div><div className="guide-workbench__joint-list">{OUTLINER_JOINTS.map(([id, label]) => <button className={selectedJoint === id ? "is-selected" : ""} key={id} onClick={() => setSelectedJoint(id)} type="button"><i />{label}</button>)}</div><div className="guide-workbench__panel-title guide-workbench__panel-title--sub"><strong>FACE &amp; HANDS</strong><span>READ-ONLY</span></div><div className="guide-workbench__read-only"><span>◉</span><div><strong>Reference data locked</strong><small>Users cannot edit pose data</small></div></div></aside><div className="guide-workbench__viewport"><span className="guide-workbench__perspective">Perspective</span><span className="guide-workbench__collection">Pose collection / {selectedJoint}</span><Canvas camera={{ fov: 32, position: [2.8, 1.3, 5.1] }} dpr={[1, 1.5]} gl={{ antialias: true }}><color attach="background" args={["#080e17"]} /><gridHelper args={[8, 20, "#17374d", "#0b1c29"]} position={[0, -1.66, 0]} /><PoseScene articulation={guideArticulation} animationProgress={transitionProgress} cameraViewRef={null} editingEnabled={false} guidesVisible={false} onMoveJoint={() => {}} onRotateJoint={() => {}} onSelectJoint={setSelectedJoint} pose={activePose} poseScale={1.35} rotation={[0, 0, 0]} rotationSnap={false} selectedJoint={selectedJoint} strikingSide={activeStep?.striking_side || ""} strikingSurface={activeStep?.striking_surface || ""} targetStrikingSide={targetStep?.striking_side || ""} targetStrikingSurface={targetStep?.striking_surface || ""} transformMode="translate" /><OrbitControls enablePan={false} maxDistance={10} minDistance={4.5} target={[0, -0.1, 0]} /></Canvas><span className="guide-skeleton__phase">{activeStep?.step_name || "Reference pose"}</span><span className="guide-workbench__status">Selected: {selectedJoint.replaceAll("_", " ")} <em>·</em> {Object.keys(activePose || {}).length} fixed points</span></div></div>
    <footer className="guide-workbench__timeline"><div className="guide-workbench__timeline-head"><div><strong>Technique timeline</strong><small>Read-only movement sequence</small></div><div className="guide-workbench__timeline-actions"><button onClick={() => setPlaying((value) => !value)} type="button">{playing ? "Pause transition" : "Play transition"}</button><span>Duration</span><output>{Math.round((activeStep?.transition_duration_ms || 1000) / 10) / 100}s</output><b>Read-only</b><button onClick={() => setPlaying(true)} type="button">Play all</button></div></div><div className="guide-workbench__track"><div className="guide-workbench__track-line"><span style={{ width: `${progress}%` }} /></div>{frames.map((frame, index) => <button className={index === activeIndex ? "is-active" : ""} key={`${frame.step_number}-${frame.step_name}`} onClick={() => setElapsed(segments.slice(0, index).reduce((sum, item) => sum + item.duration, 0))} style={{ left: `${frames.length === 1 ? 0 : (index / (frames.length - 1)) * 100}%` }} type="button"><i>{index + 1}</i><small>{frame.step_name}</small></button>)}</div><div className="guide-workbench__scrubber"><span>{activeStep?.step_name || "Reference pose"}</span><div><span style={{ width: `${progress}%` }} /></div><small>{Math.round(progress)}% · locked</small></div></footer>
  </section>;
}
